Add easyStart function
StriveMath/strive pull request #5
Opened 2021-06-07 07:41 UTC by teriaiw

2021-06-09 02:03 UTC, TamirShklaz requested changes

2021-06-09 02:03 UTC, TamirShklaz commented on src/lib/transformer.ts
> +  static easyStart() {
This function should not be in the Transformer class. This is a utility function that uses the transformer class. So make a new file called utils.ts and put this function in there.

2021-06-09 02:03 UTC, TamirShklaz commented on src/lib/transformer.ts
> +    translate(0, height)
Use Strive.translate, Strive.rotate, Strive.scale for all transformations

2021-06-09 02:03 UTC, TamirShklaz commented on src/lib/transformer.ts
> +    line(0, y, mouseX, y)
You can get the transformed mouseX and mouseY from Transformer.mouse if you use Strive.translate, Strive.scale, Strive.rotate for all transformations

2021-06-10 11:41 UTC, teriaiw commented
New branch created to follow git flow

2021-06-10 11:41 UTC, closed without merging